apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: indonesiabelajar
  region: ap-southeast-1

vpc:
  autoAllocateIPv6: false
  cidr: 172.11.0.0/16

availabilityZones: ["ap-southeast-1a", "ap-southeast-1b"]

managedNodeGroups:
  - name: private-nodegroup
    privateNetworking: true
    instanceType: t3.xlarge
    minSize: 1
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        efs: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
    logRetentionInDays: 60
