apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
stringData:
  username: mydbuser
  password: Ovrxbk1oUk7S4cRcTV70V8K9ebWPaDAz
  dbhost: mysqldatabasestack-mysql-database.cseijjkokper.ap-southeast-1.rds.amazonaws.com
  dbname: mydb
  dbport: 3306
